name: Clear databases

on:
  workflow_dispatch:

jobs:
  Clear-databases:
    runs-on: [self-hosted, windows, x64, '${{ matrix.actian-efcore-environment }}', '${{ matrix.compatibility }}']

    strategy:
      fail-fast: false
      matrix:
        actian-efcore-environment:
          - WIN64_INGRES_10_1_0
          - WIN64_ACTIANX_11_1_0
        compatibility:
          - Ingres
          - Ansi

    env:
      config: Debug

    steps:
      - uses: actions/checkout@v2

      - name: Setup Actian installation
        run: powershell .\scripts\SetupActianInstallation.ps1

      - name: Create DB user dbo
        run: powershell .\scripts\CreateDbUser.ps1 dbo

      - name: Drop test databases
        run: powershell .\scripts\DropTestDatabases.ps1
