name: Create missing test databases

on:
  workflow_dispatch:

  push:
    paths:
      - test-databases.json

jobs:
  Create-databases:
    runs-on: [self-hosted, windows, x64, '${{ matrix.dev-or-ci }}', '${{ matrix.actian-efcore-environment }}', '${{ matrix.compatibility }}']

    strategy:
      fail-fast: false
      matrix:
        dev-or-ci:
          # - Dev
          - CI
        actian-efcore-environment:
          - WIN64_INGRES_10_1_0
          - WIN64_ACTIANX_11_1_0
        compatibility:
          - Ingres
          - Ansi

    env:
      config: Debug

    steps:
      - name: Clean build directory
        run: |
          rd /s /q . 2>nul
          exit /b 0
        shell: cmd

      - uses: actions/checkout@v2

      - name: Setup Actian installation
        run: powershell .\scripts\SetupActianInstallation.ps1

      - name: Environment
        run: |
          Get-ChildItem env:

      # Create missing databases

      - name: Create missing databases
        run: dotnet run -- create-missing-test-databases
        working-directory: utils/Actian.EFCore.Build
